### PR TITLE
Hamburger Menu

### PR DESCRIPTION
**Pull request by mwisner**
screenshot 2017-06-29 20 11 20
screenshot 2017-06-29 20 11 23

### CODE REVIEW

**Comment by donaldwasserman** [comment]
Hey - I'm not sure we should have a lefthand nav, or at least make sure it's super accessible on mobile.

**Comment by donaldwasserman** [comment]
Actually, I changed my mind. I think for left-handed phone users the left-hand hamburger is better.

Just need a place to jam the icon.

**Comment by mwisner** [comment]
@donaldwasserman  we can switch it to the right as well... bunch of options: https://offirgolan.github.io/ember-burger-menu/#/?animation=scale-up&position=right

**Comment by mwisner** [comment]
Maybe we can Shawn to prototype the page layout...

**Comment by donaldwasserman** [comment]
It makes more sense the way you have it

**Comment by mwisner** [comment]
@donaldwasserman I added some content to the global page title template as well, but I noticed you had some of the logic in there for setting the info and wasn't sure how you were planning on implementing it, so I didn't finish it... (I just added some placeholder values)

**Comment by donaldwasserman** [comment]
I haven't done any of it. I just copied and pasted from mvcs

**Comment by mwisner** [comment]
Okay... it looked pretty different so I wasn't sure if you were tweaking it or not..

**Comment by mwisner** [comment]
@donaldwasserman  Added the global page title functionality as well as a simple header.

https://www.dropbox.com/s/7much0enmokx144/Screenshot%202017-07-02%2012.53.16.png?dl=0

**Comment by mwisner** [comment]
@donaldwasserman  also I just straight up stopped the ember tests in this PR... I can't for the life of me to get them to run...

**Pull request merged**
